### ISSUE TITLE
ActivityType ska ändras

### ISSUE THREAD

**Issue by hejamarcus** [tollyx/MOAS-LMS#10]
ActivityType i aktivitetsmodellen är en sträng, den ska ändras till en egen modell som aktivitetsmodellen refererar till.

**Comment by tollyx** [comment]
Ok, skriver ut det i punktform så att det blir tydligare vad som bör göras:

* Skapa ny databasmodell, `ActivityTypeModel`
    * Kommer att bara innehålla `string Name` och `bool AllowUploads` (vi kanske kommer på fler fält senare)
* Ändra `ActivityModel`'s `ActivityType` så att det är en referens till den nyligen skapade `ActivityTypeModel`
* Seeda `ActivityTypes`

**Comment by hejamarcus** [comment]
I FIXED IT #17
